# [build-system]
# requires = ["uv-build"]
# build-backend = "hatchling.build"
[build-system]
requires = ["setuptools>=46.4.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "bamp"
version = "2026.4.1"
dependencies = ["pyyaml", "click", "numpy", "pillow"]
requires-python = ">=3.10"
authors = [{ name = "David Mason", email = "davidpattenmason@gmail.com" }]
description = ""
readme = "README.md"
keywords = ["winamp"]
classifiers = ["Programming Language :: Python"]

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["src"]

[project.scripts]
convert = "bamp.cli:cli_convert"
# [project.urls]
# Homepage = "https://example.com"
# Documentation = "https://readthedocs.org"
# Repository = "https://github.com/me/spam.git"

# [project.scripts]
# spam-cli = "spam:main_cli"

# [project.entry-points."spam.magical"]
# tomatoes = "spam:main_tomatoes"
